create table public.signatures (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  name text not null,
  title text null,
  department text null,
  "isDefault" boolean null default false,
  constraint signatures_pkey primary key (id)
) TABLESPACE pg_default;